name: Build APK
on: [push]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android
      - name: Build
        run: |
          cargo install cargo-apk
          cargo apk build --release
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: target/release/apk/*.apk
          
